
const ASCII_OVO_TO_UNICODE_OVO = [
  { text: 'e~^', code: 'ê̤' },
  { text: 'e~_', code: 'ě̤' },
  { text: 'e~', code: 'e̤' },
  { text: '(e~^)', code: 'ê̤' },
  { text: '(e~_)', code: 'ě̤' },
  { text: '(e~)', code: 'é̤' },
  { text: 'i+^', code: 'ị̂' },
  { text: 'i+_', code: 'ị̌' },
  { text: 'i+', code: 'ị' },
  { text: '(i+^)', code: 'ị̂' },
  { text: '(i+_)', code: 'ị̌' },
  { text: '(i+)', code: 'ı̣́' },
  { text: 'e+^', code: 'ệ' },
  { text: 'e+_', code: 'ẹ̌' },
  { text: 'e+', code: 'ẹ' },
  { text: '(e+^)', code: 'ẹ́̂' },
  { text: '(e+_)', code: 'ẹ́̌' },
  { text: '(e+)', code: 'ẹ́' },
  { text: 'a+^', code: 'ậ' },
  { text: 'a+_', code: 'ạ̌' },
  { text: 'a+', code: 'ạ' },
  { text: '(a+^)', code: 'ạ́̂' },
  { text: '(a+_)', code: 'ạ́̌' },
  { text: '(a+)', code: 'ạ́' },
  { text: 'u+^', code: 'ụ̂' },
  { text: 'u+_', code: 'ụ̌' },
  { text: 'u+', code: 'ụ' },
  { text: '(u+^)', code: 'ụ́̂' },
  { text: '(u+_)', code: 'ụ́̌' },
  { text: '(u+)', code: 'ụ́' },
  { text: 'o+^', code: 'ộ' },
  { text: 'o+_', code: 'ọ̌' },
  { text: 'o+', code: 'ọ' },
  { text: '(o+)', code: 'ọ́' },
  { text: '(o+^)', code: 'ọ́̂' },
  { text: '(o+_)', code: 'ọ́̌' },
  { text: 'i~^', code: 'î̤' },
  { text: 'i~_', code: 'ǐ̤' },
  { text: 'i~', code: 'i̤' },
  { text: '(i~^)', code: 'ı̤́̂' },
  { text: '(i~_)', code: 'ı̤́̌' },
  { text: '(i~)', code: 'ı̤́' },
  { text: 'u~^', code: 'ṳ̂' },
  { text: 'u~_', code: 'ṳ̌' },
  { text: 'u~', code: 'ṳ' },
  { text: '(u~^)', code: 'ṳ́̂' },
  { text: '(u~_)', code: 'ṳ́̌' },
  { text: '(u~)', code: 'ṳ́' },
  { text: 'o~^', code: 'ô̤' },
  { text: 'o~_', code: 'ǒ̤' },
  { text: 'o~', code: 'o̤' },
  { text: '(o~^)', code: 'ó̤̂' },
  { text: '(o~_)', code: 'ó̤̌' },
  { text: '(o~)', code: 'ó̤' },
  { text: 'i^', code: 'î' },
  { text: 'i_', code: 'ǐ' },
  { text: 'i', code: 'i' },
  { text: '(i^)', code: 'ı́̂' },
  { text: '(i_)', code: 'ı́̌' },
  { text: '(i)', code: 'ı́' },
  { text: 'e^', code: 'ê' },
  { text: 'e_', code: 'ě' },
  { text: 'e', code: 'e' },
  { text: '(e^)', code: 'é̂' },
  { text: '(e_)', code: 'é̌' },
  { text: '(e)', code: 'é' },
  { text: 'a~^', code: 'â̤' },
  { text: 'a~_', code: 'ǎ̤' },
  { text: 'a~', code: 'a̤' },
  { text: '(a~^)', code: 'á̤̂' },
  { text: '(a~_)', code: 'á̤̌' },
  { text: '(a~)', code: 'á̤' },
  { text: 'a^', code: 'â' },
  { text: 'a_', code: 'ǎ' },
  { text: 'a', code: 'a' },
  { text: '(a^)', code: 'á̂' },
  { text: '(a_)', code: 'á̌' },
  { text: '(a)', code: 'á' },
  { text: 'o^', code: 'ô' },
  { text: 'o_', code: 'ǒ' },
  { text: 'o', code: 'o' },
  { text: '(o^)', code: 'ó̂' },
  { text: '(o_)', code: 'ó̌' },
  { text: '(o)', code: 'ó' },
  { text: 'u^', code: 'û' },
  { text: 'u_', code: 'ǔ' },
  { text: 'u', code: 'u' },
  { text: '(u^)', code: 'ú̂' },
  { text: '(u_)', code: 'ú̌' },
  { text: '(u)', code: 'ú' },
  { text: 'm+', code: 'ṃ' },
  { text: 'm', code: 'm' },
  { text: 'n+', code: 'ṇ' },
  { text: 'n', code: 'n' },
  { text: 'q', code: 'q' },
  { text: 'g?', code: 'g̀' },
  { text: 'g', code: 'g' },
  { text: '\'', code: '\'' },
  { text: '"', code: '"' },
  { text: 'd!', code: 'd̖' },
  { text: 'd?', code: 'd̗' },
  { text: 'd*', code: 'd̥' },
  { text: 'd+', code: 'ḍ' },
  { text: 'd', code: 'd' },
  { text: 'b?', code: 'b̗' },
  { text: 'b!', code: 'b̖' },
  { text: 'b', code: 'b' },
  { text: 'p!', code: 'ṕ' },
  { text: 'p*', code: 'p̊' },
  { text: 'p', code: 'p' },
  { text: 't+', code: 'ṭ' },
  { text: 't!', code: 't̖' },
  { text: 't*', code: 't̥' },
  { text: 't', code: 't' },
  { text: 'k!', code: 'k̖' },
  { text: 'k*', code: 'k̥' },
  { text: 'k+!', code: 'ḳ̖' },
  { text: 'k+', code: 'ḳ' },
  { text: 'k', code: 'k' },
  { text: 'h~', code: 'h̤' },
  { text: 'h+', code: 'ḥ' },
  { text: 'h', code: 'h' },
  { text: 'j+', code: 'ȷ̈' },
  { text: 'j~', code: 'ȷ̂' },
  { text: 'j', code: 'j' },
  { text: 's+', code: 'ṣ' },
  { text: 's', code: 's' },
  { text: 'f+', code: 'f̣' },
  { text: 'f~', code: 'f̤' },
  { text: 'f', code: 'f' },
  { text: 'v+', code: 'ṿ' },
  { text: 'v', code: 'v' },
  { text: 'z', code: 'z' },
  { text: 'c+~', code: 'c̤' },
  { text: 'c+', code: 'c̣' },
  { text: 'c', code: 'c' },
  { text: 'l+', code: 'ḷ' },
  { text: 'l*', code: 'l̥' },
  { text: 'l~', code: 'l̬' },
  { text: 'l', code: 'l' },
  { text: 'r~', code: 'r̤' },
  { text: 'r+', code: 'ṛ' },
  { text: 'r!', code: 'ŕ' },
  { text: 'r', code: 'r' },
  { text: 'x~', code: 'x̤' },
  { text: 'x+', code: 'x̣' },
  { text: 'x', code: 'x' },
  { text: 'w', code: 'w' },
  { text: 'w+', code: 'ẉ' },
  { text: 'y', code: 'y' },
  { text: '~', code: '̃' },
]

const IPA_TO_ASCII_OVO = [
  { text: 'i', code: 'i' },
  { text: 'ɪ', code: 'i+' },
  { text: 'e', code: 'e' },
  { text: 'ɛ', code: 'e+' },
  { text: 'ø', code: 'a~' },
  { text: 'ɜ', code: 'o+' },
  { text: 'ɑ', code: 'a' },
  { text: 'æ', code: 'a+' },
  { text: 'ɒ', code: 'a+' },
  { text: 'o', code: 'o' },
  { text: 'ɵ', code: 'o+' },
  { text: 'ʊ', code: 'o+' },
  { text: 'ʏ', code: 'i~' },
  { text: 'ɔ', code: 'o~' },
  { text: 'u', code: 'u' },
  { text: 'ʌ', code: 'u+' },
  { text: 'ə', code: 'u+' },
  { text: 'ʉ', code: 'u~' },
  { text: 'ɯ', code: 'u~' },
  { text: 'œ', code: 'e~' },
  { text: 'b', code: 'b' },
  { text: 'ɓ', code: 'b?' },
  { text: 'ʙ', code: 'b!' },
  { text: 'd', code: 'd' },
  { text: 'ɖ', code: 'd+' },
  { text: 'ǂ', code: 'd*' },
  { text: 'θ', code: 'c' },
  { text: 'ð', code: 'c+' },
  { text: 'f', code: 'f' },
  { text: 'ɸ', code: 'f+' },
  { text: 'g', code: 'g' },
  { text: 'ɢ', code: 'g' },
  { text: 'ɠ', code: 'g?' },
  { text: 'ʛ', code: 'g?' },
  { text: 'ɟ', code: 'gy' },
  { text: 'ʄ', code: 'g?y' },
  { text: 'h', code: 'h' },
  { text: 'ħ', code: 'h"~' },
  { text: 'ɦ', code: 'hh' },
  { text: 'x', code: 'h+' },
  { text: 'χ', code: 'h~' },
  { text: 'ç', code: 'hy' },
  { text: 'ʒ', code: 'j' },
  { text: 'ʐ', code: 'j+' },
  { text: 'ɮ', code: 'j~' },
  { text: 'ʑ', code: 'jy' },
  { text: 'k\'', code: 'k!' },
  { text: 'k', code: 'k' },
  { text: 'ǃ', code: 'k*' },
  { text: 'q\'', code: 'k+!' },
  { text: 'q', code: 'k+' },
  { text: 'm', code: 'm' },
  { text: 'n', code: 'n' },
  { text: 'ɳ', code: 'n+' },
  { text: 'ŋ', code: 'q' },
  { text: 'ɴ', code: 'q' },
  { text: 'ɲ', code: 'ny' },
  { text: 'l', code: 'l' },
  { text: 'ɭ', code: 'l+' },
  { text: 'ɬ', code: 'l~' },
  { text: 'ɫ', code: 'lr~' },
  { text: 'ʎ', code: 'ly' },
  { text: 'ǁ', code: 'l*' },
  { text: 'p', code: 'p' },
  { text: 'p\'', code: 'p!' },
  { text: 'ʘ', code: 'p*' },
  { text: 'ɹ', code: 'r' },
  { text: 'r', code: 'r!' },
  { text: 'ɽ', code: 'r+' },
  { text: 'ɣ', code: 'r~' },
  { text: 'ʁ', code: 'r~' },
  { text: 'ʀ', code: 'r~!' },
  { text: 's', code: 's' },
  { text: 't', code: 't' },
  { text: 'ʈ', code: 't+' },
  { text: 'ǀ', code: 't*' },
  { text: 'v', code: 'v' },
  { text: 'ʋ', code: 'v+' },
  { text: 'β', code: 'v+' },
  { text: 'w', code: 'w' },
  { text: 'ʍ', code: 'wh' },
  { text: 'ɰ', code: 'w+' },
  { text: 'ʃ', code: 'x' },
  { text: 'ʂ', code: 'x+' },
  { text: 'ɕ', code: 'x~' },
  { text: 'j', code: 'y' },
  { text: 'ʝ', code: 'y' },
  { text: 'y', code: 'y' },
  { text: 'ɥ', code: 'yw' },
  { text: 'z', code: 'z' },
  { text: 'ʔ', code: '\'' },
  { text: 'ʕ', code: '"' },
]

const look = {}
ASCII_OVO_TO_UNICODE_OVO.forEach(({ text }) => {
  look[text] = '^' + text.replace(/[\(\)\*\!\?\_\.\[\]\|\\\\/\^\+]/g, _ => `\\${_}`)
})

const form = text => {
  let remaining = text
  let output = []
  a:
  while (remaining.length) {
    for (let node of ASCII_OVO_TO_UNICODE_OVO) {
      const pattern = look[node.text]
      const regex = new RegExp(pattern)
      const match = remaining.match(regex)
      if (match) {
        const val = node.code
        output.push(val)
        remaining = remaining.substr(match[0].length)
        continue a
      }
    }
    break
  }
  return output.join('')
}

form.ASCII_OVO_TO_UNICODE_OVO = ASCII_OVO_TO_UNICODE_OVO
form.IPA_TO_ASCII_OVO = IPA_TO_ASCII_OVO

module.exports = form
