
const m = {
  u: {
    'grave': '\u0300',
    'acute': '\u0301',
    'dacute': '\u030B',
    'dgrave': '\u030F',
    'up': '\u0302',
    'down': '\u030C',
    'dot': '\u0307',
    'ddot': '\u0308',
    'ring': '\u030A',
  },
  d: {
    'grave': '\u0316',
    'acute': '\u0317',
    'ring': '\u0325',
    'dot': '\u0323',
    'ddot': '\u0324',
    'down': '\u032C',
    'tilde': '\u0330'
  }
}

const ASCII_OVO_TO_UNICODE_OVO = [
  { text: 'i+&^^', code: `ı${m.d.tilde}${m.d.dot}${m.u.dacute}` },
  { text: 'i+&^', code: `ı${m.d.tilde}${m.d.dot}${m.u.acute}` },
  { text: 'i+&__', code: `ı${m.d.tilde}${m.d.dot}${m.u.dgrave}` },
  { text: 'i+&_', code: `ı${m.d.tilde}${m.d.dot}${m.u.grave}` },
  { text: 'i+&', code: `i${m.d.tilde}${m.d.dot}` },
  { text: '(i+&^^)', code: `ı${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(i+&^)', code: `ı${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(i+&__)', code: `ı${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(i+&_)', code: `ı${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(i+&)', code: `ı${m.d.tilde}${m.d.dot}${m.u.dot}` },

  { text: 'i+^^', code: `ı${m.d.dot}${m.u.dacute}` },
  { text: 'i+^', code: `ı${m.d.dot}${m.u.acute}` },
  { text: 'i+__', code: `ı${m.d.dot}${m.u.dgrave}` },
  { text: 'i+_', code: `ı${m.d.dot}${m.u.grave}` },
  { text: 'i+', code: `i${m.d.dot}` },
  { text: '(i+^^)', code: `ı${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(i+^)', code: `ı${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(i+__)', code: `ı${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(i+_)', code: `ı${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(i+)', code: `ı${m.d.dot}${m.u.dot}` },

  { text: 'i~&^^', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dacute}` },
  { text: 'i~&^', code: `ı${m.d.tilde}${m.d.ddot}${m.u.acute}` },
  { text: 'i~&__', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dgrave}` },
  { text: 'i~&_', code: `ı${m.d.tilde}${m.d.ddot}${m.u.grave}` },
  { text: 'i~&', code: `i${m.d.tilde}${m.d.ddot}` },
  { text: '(i~&^^)', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(i~&^)', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(i~&__)', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(i~&_)', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(i~&)', code: `ı${m.d.tilde}${m.d.ddot}${m.u.dot}` },

  { text: 'i~^^', code: `ı${m.d.ddot}${m.u.dacute}` },
  { text: 'i~^', code: `ı${m.d.ddot}${m.u.acute}` },
  { text: 'i~__', code: `ı${m.d.ddot}${m.u.dgrave}` },
  { text: 'i~_', code: `ı${m.d.ddot}${m.u.grave}` },
  { text: 'i~', code: `i${m.d.ddot}` },
  { text: '(i~^^)', code: `ı${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(i~^)', code: `ı${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(i~__)', code: `ı${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(i~_)', code: `ı${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(i~)', code: `ı${m.d.ddot}${m.u.dot}` },

  { text: 'i&^^', code: `ı${m.d.tilde}${m.u.dacute}` },
  { text: 'i&^', code: `ı${m.d.tilde}${m.u.acute}` },
  { text: 'i&__', code: `ı${m.d.tilde}${m.u.dgrave}` },
  { text: 'i&_', code: `ı${m.d.tilde}${m.u.grave}` },
  { text: 'i&', code: `i${m.d.tilde}` },
  { text: '(i&^^)', code: `ı${m.d.tilde}${m.u.dot}${m.u.dacute}` },
  { text: '(i&^)', code: `ı${m.d.tilde}${m.u.dot}${m.u.acute}` },
  { text: '(i&__)', code: `ı${m.d.tilde}${m.u.dot}${m.u.dgrave}` },
  { text: '(i&_)', code: `ı${m.d.tilde}${m.u.dot}${m.u.grave}` },
  { text: '(i&)', code: `ı${m.d.tilde}${m.u.dot}` },

  { text: 'i^^', code: `ı${m.u.dacute}` },
  { text: 'i^', code: `ı${m.u.acute}` },
  { text: 'i__', code: `ı${m.u.dgrave}` },
  { text: 'i_', code: `ı${m.u.grave}` },
  { text: 'i', code: `i` },
  { text: '(i^^)', code: `ı${m.u.dot}${m.u.dacute}` },
  { text: '(i^)', code: `ı${m.u.dot}${m.u.acute}` },
  { text: '(i__)', code: `ı${m.u.dot}${m.u.dgrave}` },
  { text: '(i_)', code: `ı${m.u.dot}${m.u.grave}` },
  { text: '(i)', code: `ı${m.u.dot}` },

  { text: 'e+&^^', code: `e${m.d.tilde}${m.d.dot}${m.u.dacute}` },
  { text: 'e+&^', code: `e${m.d.tilde}${m.d.dot}${m.u.acute}` },
  { text: 'e+&__', code: `e${m.d.tilde}${m.d.dot}${m.u.dgrave}` },
  { text: 'e+&_', code: `e${m.d.tilde}${m.d.dot}${m.u.grave}` },
  { text: 'e+&', code: `e${m.d.tilde}${m.d.dot}` },
  { text: '(e+&^^)', code: `e${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(e+&^)', code: `e${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(e+&__)', code: `e${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(e+&_)', code: `e${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(e+&)', code: `e${m.d.tilde}${m.d.dot}${m.u.dot}` },

  { text: 'e+^^', code: `e${m.d.dot}${m.u.dacute}` },
  { text: 'e+^', code: `e${m.d.dot}${m.u.acute}` },
  { text: 'e+__', code: `e${m.d.dot}${m.u.dgrave}` },
  { text: 'e+_', code: `e${m.d.dot}${m.u.grave}` },
  { text: 'e+', code: `e${m.d.dot}` },
  { text: '(e+^^)', code: `e${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(e+^)', code: `e${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(e+__)', code: `e${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(e+_)', code: `e${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(e+)', code: `e${m.d.dot}${m.u.dot}` },

  { text: 'e&^^', code: `e${m.d.tilde}${m.u.dacute}` },
  { text: 'e&^', code: `e${m.d.tilde}${m.u.acute}` },
  { text: 'e&__', code: `e${m.d.tilde}${m.u.dgrave}` },
  { text: 'e&_', code: `e${m.d.tilde}${m.u.grave}` },
  { text: 'e&', code: `e${m.d.tilde}` },
  { text: '(e&^^)', code: `e${m.d.tilde}${m.u.dot}${m.u.dacute}` },
  { text: '(e&^)', code: `e${m.d.tilde}${m.u.dot}${m.u.acute}` },
  { text: '(e&__)', code: `e${m.d.tilde}${m.u.dot}${m.u.dgrave}` },
  { text: '(e&_)', code: `e${m.d.tilde}${m.u.dot}${m.u.grave}` },
  { text: '(e&)', code: `e${m.d.tilde}${m.u.dot}` },

  { text: 'e^^', code: `e${m.u.dacute}` },
  { text: 'e^', code: `e${m.u.acute}` },
  { text: 'e__', code: `e${m.u.dgrave}` },
  { text: 'e_', code: `e${m.u.grave}` },
  { text: 'e', code: `e` },
  { text: '(e^^)', code: `e${m.u.dot}${m.u.dacute}` },
  { text: '(e^)', code: `e${m.u.dot}${m.u.acute}` },
  { text: '(e__)', code: `e${m.u.dot}${m.u.dgrave}` },
  { text: '(e_)', code: `e${m.u.dot}${m.u.grave}` },
  { text: '(e)', code: `e${m.u.dot}` },

  { text: 'a+~&^^', code: `a${m.d.tilde}${m.d.down}${m.u.dacute}` },
  { text: 'a+~&^', code: `a${m.d.tilde}${m.d.down}${m.u.acute}` },
  { text: 'a+~&__', code: `a${m.d.tilde}${m.d.down}${m.u.dgrave}` },
  { text: 'a+~&_', code: `a${m.d.tilde}${m.d.down}${m.u.grave}` },
  { text: 'a+~&', code: `a${m.d.tilde}${m.d.down}` },
  { text: '(a+~&^^)', code: `a${m.d.tilde}${m.d.down}${m.u.dot}${m.u.dacute}` },
  { text: '(a+~&^)', code: `a${m.d.tilde}${m.d.down}${m.u.dot}${m.u.acute}` },
  { text: '(a+~&__)', code: `a${m.d.tilde}${m.d.down}${m.u.dot}${m.u.dgrave}` },
  { text: '(a+~&_)', code: `a${m.d.tilde}${m.d.down}${m.u.dot}${m.u.grave}` },
  { text: '(a+~&)', code: `a${m.d.tilde}${m.d.down}${m.u.dot}` },

  { text: 'a+~^^', code: `a${m.d.down}${m.u.dacute}` },
  { text: 'a+~^', code: `a${m.d.down}${m.u.acute}` },
  { text: 'a+~__', code: `a${m.d.down}${m.u.dgrave}` },
  { text: 'a+~_', code: `a${m.d.down}${m.u.grave}` },
  { text: 'a+~', code: `a${m.d.down}` },
  { text: '(a+~^^)', code: `a${m.d.down}${m.u.dot}${m.u.dacute}` },
  { text: '(a+~^)', code: `a${m.d.down}${m.u.dot}${m.u.acute}` },
  { text: '(a+~__)', code: `a${m.d.down}${m.u.dot}${m.u.dgrave}` },
  { text: '(a+~_)', code: `a${m.d.down}${m.u.dot}${m.u.grave}` },
  { text: '(a+~)', code: `a${m.d.down}${m.u.dot}` },

  { text: 'a+&^^', code: `a${m.d.tilde}${m.d.dot}${m.u.dacute}` },
  { text: 'a+&^', code: `a${m.d.tilde}${m.d.dot}${m.u.acute}` },
  { text: 'a+&__', code: `a${m.d.tilde}${m.d.dot}${m.u.dgrave}` },
  { text: 'a+&_', code: `a${m.d.tilde}${m.d.dot}${m.u.grave}` },
  { text: 'a+&', code: `a${m.d.tilde}${m.d.dot}` },
  { text: '(a+&^^)', code: `a${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(a+&^)', code: `a${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(a+&__)', code: `a${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(a+&_)', code: `a${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(a+&)', code: `a${m.d.tilde}${m.d.dot}${m.u.dot}` },

  { text: 'a+^^', code: `a${m.d.dot}${m.u.dacute}` },
  { text: 'a+^', code: `a${m.d.dot}${m.u.acute}` },
  { text: 'a+__', code: `a${m.d.dot}${m.u.dgrave}` },
  { text: 'a+_', code: `a${m.d.dot}${m.u.grave}` },
  { text: 'a+', code: `a${m.d.dot}` },
  { text: '(a+^^)', code: `a${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(a+^)', code: `a${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(a+__)', code: `a${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(a+_)', code: `a${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(a+)', code: `a${m.d.dot}${m.u.dot}` },

  { text: 'a~&^^', code: `a${m.d.tilde}${m.d.ddot}${m.u.dacute}` },
  { text: 'a~&^', code: `a${m.d.tilde}${m.d.ddot}${m.u.acute}` },
  { text: 'a~&__', code: `a${m.d.tilde}${m.d.ddot}${m.u.dgrave}` },
  { text: 'a~&_', code: `a${m.d.tilde}${m.d.ddot}${m.u.grave}` },
  { text: 'a~&', code: `a${m.d.tilde}${m.d.ddot}` },
  { text: '(a~&^^)', code: `a${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(a~&^)', code: `a${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(a~&__)', code: `a${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(a~&_)', code: `a${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(a~&)', code: `a${m.d.tilde}${m.d.ddot}${m.u.dot}` },

  { text: 'a~^^', code: `a${m.d.ddot}${m.u.dacute}` },
  { text: 'a~^', code: `a${m.d.ddot}${m.u.acute}` },
  { text: 'a~__', code: `a${m.d.ddot}${m.u.dgrave}` },
  { text: 'a~_', code: `a${m.d.ddot}${m.u.grave}` },
  { text: 'a~', code: `a${m.d.ddot}` },
  { text: '(a~^^)', code: `a${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(a~^)', code: `a${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(a~__)', code: `a${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(a~_)', code: `a${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(a~)', code: `a${m.d.ddot}${m.u.dot}` },

  { text: 'a&^^', code: `a${m.d.tilde}${m.u.dacute}` },
  { text: 'a&^', code: `a${m.d.tilde}${m.u.acute}` },
  { text: 'a&__', code: `a${m.d.tilde}${m.u.dgrave}` },
  { text: 'a&_', code: `a${m.d.tilde}${m.u.grave}` },
  { text: 'a&', code: `a${m.d.tilde}` },
  { text: '(a&^^)', code: `a${m.d.tilde}${m.u.dot}${m.u.dacute}` },
  { text: '(a&^)', code: `a${m.d.tilde}${m.u.dot}${m.u.acute}` },
  { text: '(a&__)', code: `a${m.d.tilde}${m.u.dot}${m.u.dgrave}` },
  { text: '(a&_)', code: `a${m.d.tilde}${m.u.dot}${m.u.grave}` },
  { text: '(a&)', code: `a${m.d.tilde}${m.u.dot}` },

  { text: 'a^^', code: `a${m.u.dacute}` },
  { text: 'a^', code: `a${m.u.acute}` },
  { text: 'a__', code: `a${m.u.dgrave}` },
  { text: 'a_', code: `a${m.u.grave}` },
  { text: 'a', code: `a` },
  { text: '(a^^)', code: `a${m.u.dot}${m.u.dacute}` },
  { text: '(a^)', code: `a${m.u.dot}${m.u.acute}` },
  { text: '(a__)', code: `a${m.u.dot}${m.u.dgrave}` },
  { text: '(a_)', code: `a${m.u.dot}${m.u.grave}` },
  { text: '(a)', code: `a${m.u.dot}` },

  { text: 'o+&^^', code: `o${m.d.tilde}${m.d.dot}${m.u.dacute}` },
  { text: 'o+&^', code: `o${m.d.tilde}${m.d.dot}${m.u.acute}` },
  { text: 'o+&__', code: `o${m.d.tilde}${m.d.dot}${m.u.dgrave}` },
  { text: 'o+&_', code: `o${m.d.tilde}${m.d.dot}${m.u.grave}` },
  { text: 'o+&', code: `o${m.d.tilde}${m.d.dot}` },
  { text: '(o+&^^)', code: `o${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(o+&^)', code: `o${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(o+&__)', code: `o${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(o+&_)', code: `o${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(o+&)', code: `o${m.d.tilde}${m.d.dot}${m.u.dot}` },

  { text: 'o+^^', code: `o${m.d.dot}${m.u.dacute}` },
  { text: 'o+^', code: `o${m.d.dot}${m.u.acute}` },
  { text: 'o+__', code: `o${m.d.dot}${m.u.dgrave}` },
  { text: 'o+_', code: `o${m.d.dot}${m.u.grave}` },
  { text: 'o+', code: `o${m.d.dot}` },
  { text: '(o+^^)', code: `o${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(o+^)', code: `o${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(o+__)', code: `o${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(o+_)', code: `o${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(o+)', code: `o${m.d.dot}${m.u.dot}` },

  { text: 'o~&^^', code: `o${m.d.tilde}${m.d.ddot}${m.u.dacute}` },
  { text: 'o~&^', code: `o${m.d.tilde}${m.d.ddot}${m.u.acute}` },
  { text: 'o~&__', code: `o${m.d.tilde}${m.d.ddot}${m.u.dgrave}` },
  { text: 'o~&_', code: `o${m.d.tilde}${m.d.ddot}${m.u.grave}` },
  { text: 'o~&', code: `o${m.d.tilde}${m.d.ddot}` },
  { text: '(o~&^^)', code: `o${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(o~&^)', code: `o${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(o~&__)', code: `o${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(o~&_)', code: `o${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(o~&)', code: `o${m.d.tilde}${m.d.ddot}${m.u.dot}` },

  { text: 'o~^^', code: `o${m.d.ddot}${m.u.dacute}` },
  { text: 'o~^', code: `o${m.d.ddot}${m.u.acute}` },
  { text: 'o~__', code: `o${m.d.ddot}${m.u.dgrave}` },
  { text: 'o~_', code: `o${m.d.ddot}${m.u.grave}` },
  { text: 'o~', code: `o${m.d.ddot}` },
  { text: '(o~^^)', code: `o${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(o~^)', code: `o${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(o~__)', code: `o${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(o~_)', code: `o${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(o~)', code: `o${m.d.ddot}${m.u.dot}` },

  { text: 'o&^^', code: `o${m.d.tilde}${m.u.dacute}` },
  { text: 'o&^', code: `o${m.d.tilde}${m.u.acute}` },
  { text: 'o&__', code: `o${m.d.tilde}${m.u.dgrave}` },
  { text: 'o&_', code: `o${m.d.tilde}${m.u.grave}` },
  { text: 'o&', code: `o${m.d.tilde}` },
  { text: '(o&^^)', code: `o${m.d.tilde}${m.u.dot}${m.u.dacute}` },
  { text: '(o&^)', code: `o${m.d.tilde}${m.u.dot}${m.u.acute}` },
  { text: '(o&__)', code: `o${m.d.tilde}${m.u.dot}${m.u.dgrave}` },
  { text: '(o&_)', code: `o${m.d.tilde}${m.u.dot}${m.u.grave}` },
  { text: '(o&)', code: `o${m.d.tilde}${m.u.dot}` },

  { text: 'o^^', code: `o${m.u.dacute}` },
  { text: 'o^', code: `o${m.u.acute}` },
  { text: 'o__', code: `o${m.u.dgrave}` },
  { text: 'o_', code: `o${m.u.grave}` },
  { text: 'o', code: `o` },
  { text: '(o^^)', code: `o${m.u.dot}${m.u.dacute}` },
  { text: '(o^)', code: `o${m.u.dot}${m.u.acute}` },
  { text: '(o__)', code: `o${m.u.dot}${m.u.dgrave}` },
  { text: '(o_)', code: `o${m.u.dot}${m.u.grave}` },
  { text: '(o)', code: `o${m.u.dot}` },

  { text: 'u+&^^', code: `u${m.d.tilde}${m.d.dot}${m.u.dacute}` },
  { text: 'u+&^', code: `u${m.d.tilde}${m.d.dot}${m.u.acute}` },
  { text: 'u+&__', code: `u${m.d.tilde}${m.d.dot}${m.u.dgrave}` },
  { text: 'u+&_', code: `u${m.d.tilde}${m.d.dot}${m.u.grave}` },
  { text: 'u+&', code: `u${m.d.tilde}${m.d.dot}` },
  { text: '(u+&^^)', code: `u${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(u+&^)', code: `u${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(u+&__)', code: `u${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(u+&_)', code: `u${m.d.tilde}${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(u+&)', code: `u${m.d.tilde}${m.d.dot}${m.u.dot}` },

  { text: 'u+^^', code: `u${m.d.dot}${m.u.dacute}` },
  { text: 'u+^', code: `u${m.d.dot}${m.u.acute}` },
  { text: 'u+__', code: `u${m.d.dot}${m.u.dgrave}` },
  { text: 'u+_', code: `u${m.d.dot}${m.u.grave}` },
  { text: 'u+', code: `u${m.d.dot}` },
  { text: '(u+^^)', code: `u${m.d.dot}${m.u.dot}${m.u.dacute}` },
  { text: '(u+^)', code: `u${m.d.dot}${m.u.dot}${m.u.acute}` },
  { text: '(u+__)', code: `u${m.d.dot}${m.u.dot}${m.u.dgrave}` },
  { text: '(u+_)', code: `u${m.d.dot}${m.u.dot}${m.u.grave}` },
  { text: '(u+)', code: `u${m.d.dot}${m.u.dot}` },

  { text: 'u~&^^', code: `u${m.d.tilde}${m.d.ddot}${m.u.dacute}` },
  { text: 'u~&^', code: `u${m.d.tilde}${m.d.ddot}${m.u.acute}` },
  { text: 'u~&__', code: `u${m.d.tilde}${m.d.ddot}${m.u.dgrave}` },
  { text: 'u~&_', code: `u${m.d.tilde}${m.d.ddot}${m.u.grave}` },
  { text: 'u~&', code: `u${m.d.tilde}${m.d.ddot}` },
  { text: '(u~&^^)', code: `u${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(u~&^)', code: `u${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(u~&__)', code: `u${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(u~&_)', code: `u${m.d.tilde}${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(u~&)', code: `u${m.d.tilde}${m.d.ddot}${m.u.dot}` },

  { text: 'u~^^', code: `u${m.d.ddot}${m.u.dacute}` },
  { text: 'u~^', code: `u${m.d.ddot}${m.u.acute}` },
  { text: 'u~__', code: `u${m.d.ddot}${m.u.dgrave}` },
  { text: 'u~_', code: `u${m.d.ddot}${m.u.grave}` },
  { text: 'u~', code: `u${m.d.ddot}` },
  { text: '(u~^^)', code: `u${m.d.ddot}${m.u.dot}${m.u.dacute}` },
  { text: '(u~^)', code: `u${m.d.ddot}${m.u.dot}${m.u.acute}` },
  { text: '(u~__)', code: `u${m.d.ddot}${m.u.dot}${m.u.dgrave}` },
  { text: '(u~_)', code: `u${m.d.ddot}${m.u.dot}${m.u.grave}` },
  { text: '(u~)', code: `u${m.d.ddot}${m.u.dot}` },

  { text: 'u&^^', code: `u${m.d.tilde}${m.u.dacute}` },
  { text: 'u&^', code: `u${m.d.tilde}${m.u.acute}` },
  { text: 'u&__', code: `u${m.d.tilde}${m.u.dgrave}` },
  { text: 'u&_', code: `u${m.d.tilde}${m.u.grave}` },
  { text: 'u&', code: `u${m.d.tilde}` },
  { text: '(u&^^)', code: `u${m.d.tilde}${m.u.dot}${m.u.dacute}` },
  { text: '(u&^)', code: `u${m.d.tilde}${m.u.dot}${m.u.acute}` },
  { text: '(u&__)', code: `u${m.d.tilde}${m.u.dot}${m.u.dgrave}` },
  { text: '(u&_)', code: `u${m.d.tilde}${m.u.dot}${m.u.grave}` },
  { text: '(u&)', code: `u${m.d.tilde}${m.u.dot}` },

  { text: 'u^^', code: `u${m.u.dacute}` },
  { text: 'u^', code: `u${m.u.acute}` },
  { text: 'u__', code: `u${m.u.dgrave}` },
  { text: 'u_', code: `u${m.u.grave}` },
  { text: 'u', code: `u` },
  { text: '(u^^)', code: `u${m.u.dot}${m.u.dacute}` },
  { text: '(u^)', code: `u${m.u.dot}${m.u.acute}` },
  { text: '(u__)', code: `u${m.u.dot}${m.u.dgrave}` },
  { text: '(u_)', code: `u${m.u.dot}${m.u.grave}` },
  { text: '(u)', code: `u${m.u.dot}` },

  { text: 'm+', code: `m${m.d.dot}` },
  { text: 'm', code: `m` },
  { text: 'n+', code: `n${m.d.dot}` },
  { text: 'n', code: `n` },
  { text: 'q', code: `q` },
  { text: 'g?', code: `g${m.u.grave}` },
  { text: 'g.', code: `g${m.u.ddot}` },
  { text: 'g@', code: `g${m.u.up}` },
  { text: 'g', code: `g` },
  { text: '\'', code: `'` },
  { text: '"', code: `"` },
  { text: 'd!', code: `d${m.d.grave}` },
  { text: 'd?', code: `d${m.d.acute}` },
  { text: 'd*', code: `d${m.d.ring}` },
  { text: 'd+', code: `d${m.d.dot}` },
  { text: 'd.', code: `d${m.d.ddot}` },
  { text: 'd@', code: `d${m.d.down}` },
  { text: 'd', code: `d` },
  { text: 'b?', code: `b${m.d.acute}` },
  { text: 'b!', code: `b${m.d.grave}` },
  { text: 'b.', code: `b${m.d.ddot}` },
  { text: 'b@', code: `b${m.d.down}` },
  { text: 'b', code: `b` },
  { text: 'p!', code: `p${m.u.acute}` },
  { text: 'p*', code: `p${m.u.ring}` },
  { text: 'p.', code: `p${m.d.ddot}` },
  { text: 'p@', code: `d${m.u.up}` },
  { text: 'p', code: `p` },
  { text: 't+', code: `t${m.d.dot}` },
  { text: 't!', code: `t${m.d.grave}` },
  { text: 't*', code: `t${m.d.ring}` },
  { text: 't.', code: `t${m.d.ddot}` },
  { text: 't@', code: `t${m.d.down}` },
  { text: 't', code: `t` },
  { text: 'k!', code: `k${m.d.grave}` },
  { text: 'k*', code: `k${m.d.ring}` },
  { text: 'k+!', code: `k${m.d.dot}${m.d.grave}` },
  { text: 'k+', code: `k${m.d.dot}` },
  { text: 'k.', code: `k${m.d.ddot}` },
  { text: 'k@', code: `k${m.d.down}` },
  { text: 'k', code: `k` },
  { text: 'h~', code: `h${m.d.ddot}` },
  { text: 'h+', code: `h${m.d.dot}` },
  { text: 'h', code: `h` },
  { text: 'j+', code: `ȷ̈` },
  { text: 'j~', code: `ȷ̂` },
  { text: 'j', code: `j` },
  { text: 's+', code: `s${m.d.dot}` },
  { text: 's@', code: `s${m.d.down}` },
  { text: 's', code: `s` },
  { text: 's!', code: `s${m.u.acute}` },
  { text: 'f+', code: `f${m.d.dot}` },
  { text: 'f~', code: `f${m.d.ddot}` },
  { text: 'f@', code: `f${m.d.down}` },
  { text: 'f', code: `f` },
  { text: 'v+', code: `v${m.d.dot}` },
  { text: 'v', code: `v` },
  { text: 'z', code: `z` },
  { text: 'c+~', code: `c${m.d.ddot}` },
  { text: 'c+', code: `c${m.d.dot}` },
  { text: 'c', code: `c` },
  { text: 'l+', code: `l${m.d.dot}` },
  { text: 'l*', code: `l${m.d.ring}` },
  { text: 'l~', code: `l̬` },
  { text: 'l', code: `l` },
  { text: 'r~', code: `r${m.d.ddot}` },
  { text: 'r+', code: `r${m.d.dot}` },
  { text: 'r!', code: `r${m.u.acute}` },
  { text: 'r', code: `r` },
  { text: 'x~', code: `x${m.d.ddot}` },
  { text: 'x+', code: `x${m.d.dot}` },
  { text: 'x@', code: `x${m.d.down}` },
  { text: 'x', code: `x` },
  { text: 'w', code: `w` },
  { text: 'w+', code: `w${m.d.dot}` },
  { text: 'y', code: `y` },
  { text: 'y+', code: `y${m.u.dot}` },
]

const IPA_TO_ASCII_OVO = [
  { text: 'i', code: 'i' },
  { text: 'ɪ', code: 'i+' },
  { text: 'e', code: 'e' },
  { text: 'ɛ', code: 'e+' },
  { text: 'ø', code: 'a~' },
  { text: 'ɜ', code: 'o+' },
  { text: 'ɑ', code: 'a' },
  { text: 'ɒ', code: 'a' },
  { text: 'ä', code: 'a' },
  { text: 'æ', code: 'a+' },
  { text: 'æ', code: 'a+' },
  { text: 'o', code: 'o' },
  { text: 'ɵ', code: 'o+' },
  { text: 'ʊ', code: 'o+' },
  { text: 'ɤ', code: 'o+' },
  { text: 'ʏ', code: 'i~' },
  { text: 'ɨ', code: 'i~' },
  { text: 'y', code: 'i~' },
  { text: 'ɔ', code: 'o~' },
  { text: 'u', code: 'u' },
  { text: 'ʌ', code: 'u+' },
  { text: 'ə', code: 'u+' },
  { text: 'ɞ', code: 'u+' },
  { text: 'ʉ', code: 'u' },
  { text: 'ɯ', code: 'o+' },
  { text: 'œ', code: 'e~' },
  { text: 'ɶ', code: 'e~' },
  { text: 'b', code: 'b' },
  { text: 'ɓ', code: 'b?' },
  { text: 'ʙ', code: 'b!' },
  { text: 'd', code: 'd' },
  { text: 'ɖ', code: 'd+' },
  { text: 'ǂ', code: 'd*' },
  { text: 'θ', code: 'c' },
  { text: 'ð', code: 'c+' },
  { text: 'f', code: 'f' },
  { text: 'ɸ', code: 'f+' },
  { text: 'g', code: 'g' },
  { text: 'ɢ', code: 'g' },
  { text: 'ɠ', code: 'g?' },
  { text: 'ʛ', code: 'g?' },
  { text: 'ɟ', code: 'gy' },
  { text: 'ʄ', code: 'g?y' },
  { text: 'h', code: 'h' },
  { text: 'ħ', code: 'h+' },
  { text: 'ɦ', code: 'hh' },
  { text: 'x', code: 'h+' },
  { text: 'χ', code: 'h+' },
  { text: 'ç', code: 'hy' },
  { text: 'ʒ', code: 'j' },
  { text: 'ʐ', code: 'j+' },
  { text: 'ɮ', code: 'j~' },
  { text: 'ʑ', code: 'jy' },
  { text: 'k\'', code: 'k!' },
  { text: 'k', code: 'k' },
  { text: 'ǃ', code: 'k*' },
  { text: 'q\'', code: 'k+!' },
  { text: 'q', code: 'k+' },
  { text: 'm', code: 'm' },
  { text: 'n', code: 'n' },
  { text: 'ɳ', code: 'n+' },
  { text: 'ŋ', code: 'q' },
  { text: 'ɴ', code: 'q' },
  { text: 'ɲ', code: 'ny' },
  { text: 'l', code: 'l' },
  { text: 'ɭ', code: 'l+' },
  { text: 'ɬ', code: 'l~' },
  { text: 'ɫ', code: 'lr~' },
  { text: 'ʎ', code: 'ly' },
  { text: 'ǁ', code: 'l*' },
  { text: 'p', code: 'p' },
  { text: 'p\'', code: 'p!' },
  { text: 'ʘ', code: 'p*' },
  { text: 'ɹ', code: 'r' },
  { text: 'r', code: 'r!' },
  { text: 'ɽ', code: 'r+' },
  { text: 'ɣ', code: 'r~' },
  { text: 'ʁ', code: 'r~' },
  { text: 'ʀ', code: 'r~!' },
  { text: 's', code: 's' },
  { text: 't', code: 't' },
  { text: 'ʈ', code: 't+' },
  { text: 'ǀ', code: 't*' },
  { text: 'v', code: 'v' },
  { text: 'ʋ', code: 'v+' },
  { text: 'ⱱ', code: 'v+' },
  { text: 'β', code: 'v+' },
  { text: 'w', code: 'w' },
  { text: 'ʍ', code: 'wh' },
  { text: 'ɰ', code: 'w+' },
  { text: 'ʃ', code: 'x' },
  { text: 'ʂ', code: 'x+' },
  { text: 'ɕ', code: 'x~' },
  { text: 'j', code: 'y' },
  { text: 'ʝ', code: 'y' },
  { text: 'ɥ', code: 'yw' },
  { text: 'z', code: 'z' },
  { text: 'ʔ', code: '\'' },
  { text: 'ʕ', code: '"' },
]

const look = {}
ASCII_OVO_TO_UNICODE_OVO.forEach(({ text }) => {
  look[text] = '^' + text.replace(/[\(\)\*\!\?\_\.\[\]\|\\\\/\^\+]/g, _ => `\\${_}`)
})

const form = text => {
  let remaining = text.replace(/([A-Z])/g, (_, $1) => `${$1.toLowerCase()}+`)
  let output = []
  a:
  while (remaining.length) {
    for (let node of ASCII_OVO_TO_UNICODE_OVO) {
      const pattern = look[node.text]
      const regex = new RegExp(pattern)
      const match = remaining.match(regex)
      if (match) {
        const val = node.code
        output.push(val)
        remaining = remaining.substr(match[0].length)
        continue a
      }
    }
    break
  }
  return output.join('')
}

form.ASCII_OVO_TO_UNICODE_OVO = ASCII_OVO_TO_UNICODE_OVO
form.IPA_TO_ASCII_OVO = IPA_TO_ASCII_OVO

module.exports = form
