// TODO: build the list of possible vowels and
// consonant clusters from Wiktionary and other IPA sources.

export const VOWEL_CLUSTERS = [
  'aɪ', // as in high (English)
  'aʊ', // as in now (English)
  'eɪ', // as in day (English)
  'oʊ', // as in go (English)
  'ɔɪ', // as in boy (English)
  'iə', // as in idea (British English)
  'eə', // as in hair (British English)
  'ʊə', // as in tour (British English)
  'øɪ', // as in neu (German)
  'aɛ', // as in ai (Portuguese)
  'aɔ', // as in mão (Portuguese)
  'wa', // as in agua (Spanish)
  'we', // as in huevo (Spanish)
  'wi', // as in huir (Spanish)
  'uɛ', // as in cuesta (Spanish)
  'ai', // as in mai (Italian)
  'au', // as in causa (Italian)
  'ɔi', // as in poi (Italian)
  'iɔ', // as in fiore (Italian)
  'ua', // as in guarda (Italian)
  'ie', // as in hielo (Spanish)
  'uo', // as in buono (Italian)
  'øy', // as in bøyning (Norwegian)
  'ɐʊ', // as in haus (German)
  'eɪ', // as in gehen (German)
  'ɛi', // as in Heidi (German)
  'ui', // as in ruido (Spanish)
  'ei̯', // as in mein (German)
  'ai̯', // as in beim (German)
  'ɔu̯', // as in auto (German)
  'ɔɪ̯', // as in freund (German)
  'ia', // as in kiwi (Portuguese)
  'iu', // as in viu (Portuguese)
  'ɯi', // as in 위 (Korean)
  'ai̯', // as in kaitse (Estonian)
  'ou', // as in house (Mandarin)
  'ei', // as in fei (Mandarin)
  'io', // as in dio (Italian)
  'ɔɛ', // as in loer (Dutch)
  'iu', // as in ciuccio (Italian)
  'ja', // as in yak (Russian)
  'ju', // as in use (English)
  'wa', // as in want (Dutch)
  'je', // as in je (French)
  'yɛ', // as in suède (French)
  'ui̯', // as in ruido (Spanish)
  'ɛu', // as in heu (French)
  'uo̯', // as in suo (Italian)
  'i̯a', // as in pian (Italian)
  'ɨu', // as in cui (Romanian)
  'aɪə', // as in fire (British English)
  'aʊə', // as in hour (British English)
  'eɪə', // as in layer (British English)
  'ɔɪə', // as in employer (British English)
  'oʊə', // as in lower (British English)
  'jʊə', // as in cure (British English)
  'waɪə', // as in choir (British English)
  'weɪə', // as in waya (Scottish Gaelic)
  'iuə', // as in siua (Scottish Gaelic)
  'eɪɚ', // as in player (American English)
  'aʊɚ', // as in power (American English)
  'iʊə', // as in fiuola (Romanian)
  'uai', // as in guayaba (Spanish)
  'iau', // as in iauto (Romanian)
  'oua', // as in două (Romanian)
  'uei', // as in dueño (Spanish)
  'iaɪ', // as in iaio (Catalan)
  'iou', // as in fiou (Portuguese)
  'ɨai', // as in pai (Romanian)
  'ɔeɪ', // as in poeta (Spanish)
  'ieɪ', // as in viejito (Spanish)
  'iou̯', // as in ciudat (Romanian)
  'ɪuə', // as in piua (Romanian)
  'uoi', // as in buoia (Italian)
  'iau', // as in iau (Romanian)
  'uɛu', // as in queuing (English)
  'aiu', // as in aiuto (Italian)
  'ueɪ', // as in cuenta (Spanish)
  'iau̯', // as in iau (Romanian)
  'waɪʊ', // as in why oh (English)
  'oai', // as in koai (Hawaiian)
  'ioɪ', // as in ioi (Hawaiian)
  'ɛoi', // as in leoí (Galician)
  'uiə', // as in ruina (Spanish)
  'oiə', // as in coiote (Portuguese)
  'aua', // as in aula (Italian)
  'iei', // as in leiio (Italian)
  'ouɪ', // as in Louie (English)
  'ioʊ', // as in piano (Italian)
  'uai', // as in suai (Portuguese)
  'oai', // as in boaí (Portuguese)
  'iui', // as in viuír (Galician)
  'uei', // as in huella (Spanish)
  'aiu', // as in maiuta (Sicilian)
  'uaɪ', // as in waima (Hawaiian)
  'uɔɪ', // as in luoi (Italian)
  'ieɪ', // as in piezo (Spanish)
  'iau̯', // as in liau (Italian)
  'ioe', // as in ioele (Italian)
  'eio', // as in neiou (Hawaiian)
]

export const CONSONANT_CLUSTERS = [
  'bl', // as in blue (English)
  'br', // as in bread (English)
  'pl', // as in plant (English)
  'pr', // as in price (English)
  'tr', // as in tree (English)
  'kl', // as in clean (English)
  'kr', // as in crab (English)
  'dr', // as in drive (English)
  'fr', // as in friend (English)
  'fl', // as in fly (English)
  'st', // as in stop (English)
  'sp', // as in sport (English)
  'sk', // as in sky (English)
  'sm', // as in smile (English)
  'sn', // as in snow (English)
  'sl', // as in slow (English)
  'gr', // as in green (English)
  'gl', // as in glove (English)
  'tw', // as in twin (English)
  'kw', // as in quick (English)
  'θr', // as in three (English)
  'ʃr', // as in shrug (English)
  'ʧr', // as in try (English)
  'mj', // as in mieux (French)
  'pw', // as in pueblo (Spanish)
  'fj', // as in fjord (Norwegian)
  'trʲ', // as in трюк (Russian)
  'dj', // as in djup (Swedish)
  'lj', // as in ljus (Swedish)
  'ʒv', // as in žvaigždė (Lithuanian)
  'ts', // as in tsunami (Japanese)
  'dz', // as in pizza (Italian)
  'ks', // as in box (English)
  'ps', // as in psychology (English)
  'pt', // as in ptolemy (English)
  'gn', // as in gnocchi (Italian)
  'ʃp', // as in Spiel (German)
  'ʃt', // as in Stein (German)
  'xt', // as in nacht (German)
  'fn', // as in fnugg (Norwegian)
  'tk', // as in tko (Croatian)
  'mn', // as in mnoga (Polish)
  'ʃn', // as in Schnee (German)
  'mp', // as in kamp (Dutch)
  'ŋk', // as in king (English)
  'ɖʐ', // as in джинсы (Russian)
  'sf', // as in sfera (Italian)
  'rm', // as in hermosa (Spanish)
  'lm', // as in alma (Spanish)
  'rv', // as in rval (Czech)
  'str', // as in street (English)
  'spl', // as in splash (English)
  'spr', // as in spring (English)
  'skr', // as in scratch (English)
  'skl', // as in skleros (Greek)
  'skt', // as in askt (Danish)
  'ʃtr', // as in Strasse (German)
  'ʃpl', // as in splashen (German)
  'splʲ', // as in сплю (Russian)
  'tsr', // as in tsrmon (Hebrew)
  'mpl', // as in ample (English)
  'ndr', // as in android (English)
  'ŋkl', // as in uncle (English)
  'ŋgr', // as in angry (English)
  'kst', // as in next (English)
  'lbr', // as in albricias (Spanish)
  'lkr', // as in alkratos (Greek)
  'drʒ', // as in джокер (Russian)
  'gdr', // as in dragged (English)
  'tʃr', // as in tree (English)
  'plʃ', // as in plšost (Czech)
  'ŋkt', // as in banked (English)
  'ʃkr', // as in schreiben (German)
  'ʃpr', // as in sprich (German)
  'skw', // as in squeeze (English)
  'ftr', // as in after (English)
  'psk', // as in Pskov (Russian)
  'mplʲ', // as in imple (Spanish)
  'strʲ', // as in стрель (Russian)
  'ptk', // as in apteek (Estonian)
  'sprʲ', // as in спринт (Russian)
  'sfr', // as in sfreccia (Italian)
  'rtn', // as in partner (English)
  'kstr', // as in extra (English)
  'ftn', // as in softness (English)
  'mpt', // as in tempt (English)
  'drt', // as in dirt (English)
  'ndrʲ', // as in андрюша (Russian)
  'lbrʲ', // as in лбрюшка (Russian)
  'vrz', // as in vrzati (Slovak)
  'skrʲ', // as in скреп (Russian)
  'strj', // as in strepitous (English)
  'dzr', // as in dzra (Georgian)
  'spn', // as in span (English)
  'stn', // as in stern (English)
  'ɲdr', // as in ñdrangheta (Italian)
  'sgr', // as in sguardo (Italian)
]
